using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExamineSettingsWindow : FancyWindow
{
    public event Action? OnReset;
    public event Action<(CustomExamineData publicData, CustomExamineData subtleData, bool inHeatEnabled, bool inRutEnabled)>? OnSave;

    public CustomExamineSettingsWindow()
    {
        RobustXamlLoader.Load(this);

        ResetButton.OnPressed += _ => OnReset?.Invoke();
        SaveButton.OnPressed += _ => OnSave?.Invoke((Public.GetData(), Subtle.GetData(), InHeatToggle.Pressed, InRutToggle.Pressed));
    }

    public void SetData(CustomExamineData publicData, CustomExamineData subtleData, bool inHeatEnabled, bool inRutEnabled, bool force = false)
    {
        Public.SetData(publicData, force);
        Subtle.SetData(subtleData, force);
        InHeatToggle.Pressed = inHeatEnabled;
        InRutToggle.Pressed = inRutEnabled;
    }
}

